ProblemStatement_PromotionEngine/Models/CartModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProblemStatement_PromotionEngine.Models
{
    public class CartModel
    {
        public int CartId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        
        public List<CartModel> CartList { get; set; }
    }
}

ProblemStatement_PromotionEngine/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProblemStatement_PromotionEngine.Models
{
    public class Offer
    {
        public int ProductId { get; set; }
        public string OfferName { get; set; }
        public decimal OfferPrice { get; set; }


    }
    public class ProductWiseOffer : Offer
    {
        public decimal productOfferPrice(int productId, decimal offerPrice, int productCount)
        {
            ProductModel obj = new ProductModel();
            if (obj.getProductById(productId) != null)
            {

            }
            return 0;
        }
    }

}

ProblemStatement_PromotionEngine/Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProblemStatement_PromotionEngine.Models
{
    public class ProductModel
    {

        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public List<ProductModel> productList = new List<ProductModel>();

        // private List<Product> products;

       

        public List<ProductModel> getAllProductList()
        {
            List<ProductModel> productList = new List<ProductModel>()
            {
                new ProductModel{Id = 1,ProductName = "A",Price = 50},
                new ProductModel{Id = 2,ProductName = "B",Price = 30},
                new ProductModel{Id = 3,ProductName = "C",Price = 20},
                new ProductModel{Id = 4,ProductName = "D",Price = 10},
            };
            return productList;
        }
        public  ProductModel getProductById(int productId)
        {
           return (from u in getAllProductList()
                   where u.Id == productId
                   select u).FirstOrDefault();
        }
    }
}

ProblemStatement_PromotionEngine/Controllers/CartController.cs
using ProblemStatement_PromotionEngine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProblemStatement_PromotionEngine.Controllers
{
    public class CartController : Controller
    {
        ProductModel objProduct = new ProductModel();
        // GET: Cart

        public ActionResult Index()
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            ViewBag.carList = cart;
            return View();
        }
        public ActionResult Remove(string id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];


            var isExits = (from u in cart
                           where u.ProductId == Convert.ToInt32(id)
                           select u).FirstOrDefault();

            if (isExits.Quantity > 1)
            {
                foreach (var item in cart.Where(w => w.ProductId == Convert.ToInt32(id)))
                {
                    item.Quantity = isExits.Quantity - 1;
                }
            }
            else
            {
                cart.Remove(isExits);
            }

            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
    }
}

ProblemStatement_PromotionEngine/Controllers/ShoppingController.cs
using ProblemStatement_PromotionEngine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProblemStatement_PromotionEngine.Controllers
{
    public class ShoppingController : Controller
    {
        ProductModel _objProductModel = new ProductModel();
        CartModel _objCart = new CartModel();
        // GET: Shopping
        public ActionResult Index()
        {
            
            ViewBag.productList = _objProductModel.getAllProductList();
            return View();
          
        }
        public ActionResult AddToCart(string id)
        {

            var productDetails = _objProductModel.getProductById(Convert.ToInt32(id));


            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { CartId = cart.Count + 1, ProductId = productDetails.Id, Quantity = 1 });
                _objCart.CartList = cart;
                Session["cart"] = cart;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                int index = isExist(productDetails.Id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new CartModel { CartId = cart.Count + 1, ProductId = productDetails.Id, Quantity = 1 });
                }
                _objCart.CartList = cart;
                Session["cart"] = cart;
            }

            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].ProductId == id)
                    return i;
            return -1;
        }
    }
}

ProblemStatement_PromotionEngine/Views/Cart/Index.cshtml
@{
    Layout = null;
}
@using ProblemStatement_PromotionEngine.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>
    <h3>Cart Page</h3>
    <table cellpadding="2" cellspacing="2" border="1">
        <tr>

            <th>Id</th>
            <th>ProductId</th>
            <th>Quantity</th>
        </tr>
        @if (ViewBag.carList != null)
        {
            foreach (CartModel item in ViewBag.carList)
            {
                <tr>
                    
                    <td><a href="@Url.Action("Remove", "Cart", new { id = item.CartId })">Remove</a></td>
                    <td>@item.ProductId</td>
                    <td>@item.Quantity</td>

                </tr>
            }
            <tr>
                <td align="right" colspan="2">Sum</td>
                <td>
                  
                </td>
            </tr>
        }
    </table>
    <br>
    <a href="@Url.Action("Index", "Shopping")">Continue Shopping</a>
</body>
</html>

ProblemStatement_PromotionEngine/Views/Shopping/Index.cshtml
@{
    Layout = null;
    var CartItemCount = (List<CartModel>)Session["cart"];
}

@using ProblemStatement_PromotionEngine.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Shopping</title>
</head>
<body>

    <h3>Products List</h3>
    <table cellpadding="2" cellspacing="2" border="1">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
            <th>Buy</th>
        </tr>
        @foreach (ProductModel product in ViewBag.productList)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.ProductName</td>
                <td>@product.Price</td>
                <td align="center">
                    <a href="@Url.Action("AddToCart", "Shopping", new { id = product.Id })">Add to Cart</a>
                </td>
            </tr>
        }
    </table>
    
    <h4>Item In Cart</h4>
    <p>
        @if (CartItemCount != null)
        {
            @CartItemCount.Count.ToString();
        }

        <a href="@Url.Action("Index", "Cart")">View Cart</a>
    </p>
    
</body>
</html>